/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package views.trajes;
import java.awt.Color;
/**
 *
 * @author DELL
 */
public class acercade extends javax.swing.JPanel {

    /**
     * Creates new form actualizar2
     */
    public acercade() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        tituloEliminar = new javax.swing.JLabel();
        tituloEliminar1 = new javax.swing.JLabel();
        tituloEliminar2 = new javax.swing.JLabel();
        tituloEliminar3 = new javax.swing.JLabel();
        tituloEliminar4 = new javax.swing.JLabel();
        tituloEliminar5 = new javax.swing.JLabel();
        tituloEliminar6 = new javax.swing.JLabel();
        tituloEliminar7 = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(102, 0, 0));

        tituloEliminar.setFont(new java.awt.Font("Mongolian Baiti", 1, 24)); // NOI18N
        tituloEliminar.setForeground(new java.awt.Color(255, 255, 255));
        tituloEliminar.setText("Programadores");

        tituloEliminar1.setFont(new java.awt.Font("Mongolian Baiti", 1, 36)); // NOI18N
        tituloEliminar1.setForeground(new java.awt.Color(255, 255, 255));
        tituloEliminar1.setText("Acerca de");

        tituloEliminar2.setFont(new java.awt.Font("Mongolian Baiti", 1, 18)); // NOI18N
        tituloEliminar2.setForeground(new java.awt.Color(255, 255, 255));
        tituloEliminar2.setText("Jota Emilio Lopez");

        tituloEliminar3.setFont(new java.awt.Font("Mongolian Baiti", 1, 18)); // NOI18N
        tituloEliminar3.setForeground(new java.awt.Color(255, 255, 255));
        tituloEliminar3.setText("2259394");

        tituloEliminar4.setFont(new java.awt.Font("Mongolian Baiti", 1, 18)); // NOI18N
        tituloEliminar4.setForeground(new java.awt.Color(255, 255, 255));
        tituloEliminar4.setText("Alejandro Martinez");

        tituloEliminar5.setFont(new java.awt.Font("Mongolian Baiti", 1, 18)); // NOI18N
        tituloEliminar5.setForeground(new java.awt.Color(255, 255, 255));
        tituloEliminar5.setText("2259565");

        tituloEliminar6.setFont(new java.awt.Font("Mongolian Baiti", 1, 18)); // NOI18N
        tituloEliminar6.setForeground(new java.awt.Color(255, 255, 255));
        tituloEliminar6.setText("Juan Miguel Posso");

        tituloEliminar7.setFont(new java.awt.Font("Mongolian Baiti", 1, 18)); // NOI18N
        tituloEliminar7.setForeground(new java.awt.Color(255, 255, 255));
        tituloEliminar7.setText("2259610");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(177, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(tituloEliminar4)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(tituloEliminar2)
                                .addComponent(tituloEliminar)
                                .addComponent(tituloEliminar6)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGap(39, 39, 39)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(tituloEliminar3)
                                        .addComponent(tituloEliminar7)))))
                        .addGap(168, 168, 168))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(tituloEliminar5)
                        .addGap(200, 200, 200))))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                    .addContainerGap(177, Short.MAX_VALUE)
                    .addComponent(tituloEliminar1)
                    .addGap(169, 169, 169)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(101, 101, 101)
                .addComponent(tituloEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(tituloEliminar2, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tituloEliminar3, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(tituloEliminar4, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(tituloEliminar5, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 56, Short.MAX_VALUE)
                .addComponent(tituloEliminar6, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tituloEliminar7, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(46, 46, 46))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(37, 37, 37)
                    .addComponent(tituloEliminar1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(430, Short.MAX_VALUE)))
        );

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 500, 500));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel tituloEliminar;
    private javax.swing.JLabel tituloEliminar1;
    private javax.swing.JLabel tituloEliminar2;
    private javax.swing.JLabel tituloEliminar3;
    private javax.swing.JLabel tituloEliminar4;
    private javax.swing.JLabel tituloEliminar5;
    private javax.swing.JLabel tituloEliminar6;
    private javax.swing.JLabel tituloEliminar7;
    // End of variables declaration//GEN-END:variables
}
