/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package views.trajes;

import java.awt.Color;

import javax.swing.JOptionPane;

import controllers.TiendaController;
import models.PaisEnum;
import models.TrajeModel;

/**
 *
 * @author DELL
 */
public class actualizar extends javax.swing.JPanel {

    public actualizar(TiendaController controller) {
        initComponents();
        this.controller = controller;
    }

    TiendaController controller;

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        tituloinsertar = new javax.swing.JLabel();
        subtituloNombre = new javax.swing.JLabel();
        nombretxt = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        subtituloPais = new javax.swing.JLabel();
        paistxt = new javax.swing.JTextField();
        paises = new javax.swing.JComboBox<PaisEnum>(PaisEnum.values());
        jSeparator2 = new javax.swing.JSeparator();
        subtituloMaterial = new javax.swing.JLabel();
        materialtxt = new javax.swing.JTextField();
        jSeparator4 = new javax.swing.JSeparator();
        subtituloPrecio = new javax.swing.JLabel();
        preciotxt = new javax.swing.JTextField();
        jSeparator3 = new javax.swing.JSeparator();
        botonGuardarDatosInsertar = new javax.swing.JButton();
        buscar = new javax.swing.JButton();

        setPreferredSize(new java.awt.Dimension(500, 500));

        jPanel1.setBackground(new java.awt.Color(102, 0, 0));

        tituloinsertar.setFont(new java.awt.Font("Mongolian Baiti", 1, 36)); // NOI18N
        tituloinsertar.setForeground(new java.awt.Color(255, 255, 255));
        tituloinsertar.setText("Actualizar");

        subtituloNombre.setFont(new java.awt.Font("Mongolian Baiti", 1, 18)); // NOI18N
        subtituloNombre.setForeground(new java.awt.Color(255, 255, 255));
        subtituloNombre.setText("Nombre");

        nombretxt.setBackground(new java.awt.Color(51, 51, 51));
        nombretxt.setFont(new java.awt.Font("Lucida Sans Unicode", 0, 12)); // NOI18N
        nombretxt.setForeground(new java.awt.Color(153, 153, 153));
        nombretxt.setText("Ingrese el nombre del traje");
        nombretxt.setBorder(null);
        nombretxt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                nombretxtMousePressed(evt);
            }
        });
        nombretxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nombretxtActionPerformed(evt);
            }
        });

        jSeparator1.setForeground(new java.awt.Color(0, 0, 0));

        subtituloPais.setFont(new java.awt.Font("Mongolian Baiti", 1, 18)); // NOI18N
        subtituloPais.setForeground(new java.awt.Color(255, 255, 255));
        subtituloPais.setText("Pais");

        paistxt.setBackground(new java.awt.Color(51, 51, 51));
        paistxt.setFont(new java.awt.Font("Lucida Sans Unicode", 0, 12)); // NOI18N
        paistxt.setForeground(new java.awt.Color(153, 153, 153));
        paistxt.setText("Ingrese el pais de fabricacion");
        paistxt.setBorder(null);
        paises.setBackground(new java.awt.Color(51, 51, 51));
        paises.setFont(new java.awt.Font("Lucida Sans Unicode", 0, 12)); // NOI18N
        paises.setForeground(new java.awt.Color(153, 153, 153));
        paises.setBorder(null);
        paises.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                System.out.println(evt);
            }
        });
        paistxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                paistxtActionPerformed(evt);
            }
        });

        jSeparator2.setForeground(new java.awt.Color(0, 0, 0));

        subtituloMaterial.setFont(new java.awt.Font("Mongolian Baiti", 1, 18)); // NOI18N
        subtituloMaterial.setForeground(new java.awt.Color(255, 255, 255));
        subtituloMaterial.setText("Material");

        materialtxt.setBackground(new java.awt.Color(51, 51, 51));
        materialtxt.setFont(new java.awt.Font("Lucida Sans Unicode", 0, 12)); // NOI18N
        materialtxt.setForeground(new java.awt.Color(153, 153, 153));
        materialtxt.setText("Ingrese el material del traje");
        materialtxt.setBorder(null);
        materialtxt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                materialtxtMousePressed(evt);
            }
        });
        materialtxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                materialtxtActionPerformed(evt);
            }
        });

        jSeparator4.setForeground(new java.awt.Color(0, 0, 0));

        subtituloPrecio.setFont(new java.awt.Font("Mongolian Baiti", 1, 18)); // NOI18N
        subtituloPrecio.setForeground(new java.awt.Color(255, 255, 255));
        subtituloPrecio.setText("Precio");

        preciotxt.setBackground(new java.awt.Color(51, 51, 51));
        preciotxt.setFont(new java.awt.Font("Lucida Sans Unicode", 0, 12)); // NOI18N
        preciotxt.setForeground(new java.awt.Color(153, 153, 153));
        preciotxt.setText("Ingrese el precio del traje");
        preciotxt.setBorder(null);
        preciotxt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                preciotxtMousePressed(evt);
            }
        });
        preciotxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                preciotxtActionPerformed(evt);
            }
        });

        jSeparator3.setForeground(new java.awt.Color(0, 0, 0));

        botonGuardarDatosInsertar.setBackground(new java.awt.Color(204, 204, 204));
        botonGuardarDatosInsertar.setText("Buscar");
        botonGuardarDatosInsertar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        botonGuardarDatosInsertar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                if(index != -1){
botonGuardarDatosInsertarActionPerformed(evt);
                }else{
                    botonBuscarTrajeActionPerformed(evt);
                }
                
            }
        });
        buscar.setBackground(new java.awt.Color(204, 204, 204));
        buscar.setText("Buscar Traje");
        buscar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        buscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonBuscarTrajeActionPerformed(evt);
                ;
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGap(135, 135, 135)
                                                .addComponent(tituloinsertar))
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGap(93, 93, 93)
                                                .addComponent(subtituloNombre)
                                                .addGap(24, 24, 24)
                                                .addGroup(jPanel1Layout
                                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(jSeparator1,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE, 190,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(nombretxt, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGap(108, 108, 108)
                                                .addComponent(subtituloPrecio)
                                                .addGroup(jPanel1Layout
                                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                                .addGap(29, 29, 29)
                                                                .addComponent(preciotxt,
                                                                        javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                        javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                        javax.swing.GroupLayout.PREFERRED_SIZE))
                                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                                .addGap(18, 18, 18)
                                                                .addComponent(jSeparator3,
                                                                        javax.swing.GroupLayout.PREFERRED_SIZE, 190,
                                                                        javax.swing.GroupLayout.PREFERRED_SIZE))))
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout
                                                .createSequentialGroup()
                                                .addGroup(jPanel1Layout
                                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                                .addComponent(subtituloMaterial)
                                                                .addGap(24, 24, 24))
                                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                                .addComponent(subtituloPais)
                                                                .addGap(46, 46, 46)))
                                                .addGroup(jPanel1Layout
                                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(jSeparator2,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE, 190,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(paises, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        // .addComponent(paistxt,
                                                        // javax.swing.GroupLayout.PREFERRED_SIZE,
                                                        // javax.swing.GroupLayout.DEFAULT_SIZE,
                                                        // javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(materialtxt,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(jSeparator4,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE, 190,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addContainerGap(131, Short.MAX_VALUE))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(botonGuardarDatosInsertar, javax.swing.GroupLayout.PREFERRED_SIZE, 103,
                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(193, 193, 193)));
        jPanel1Layout.setVerticalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(tituloinsertar, javax.swing.GroupLayout.PREFERRED_SIZE, 33,
                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED,
                                        javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout
                                                .createSequentialGroup()
                                                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                        javax.swing.GroupLayout.DEFAULT_SIZE,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(1, 1, 1))
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout
                                                .createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                .addComponent(subtituloNombre, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                        33, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(nombretxt, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                        javax.swing.GroupLayout.DEFAULT_SIZE,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(42, 42, 42)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        // .addComponent(paistxt, javax.swing.GroupLayout.PREFERRED_SIZE,
                                        // javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(paises, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(subtituloPais, javax.swing.GroupLayout.PREFERRED_SIZE, 33,
                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10,
                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(35, 35, 35)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(materialtxt, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                        javax.swing.GroupLayout.DEFAULT_SIZE,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 10,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addComponent(subtituloMaterial, javax.swing.GroupLayout.PREFERRED_SIZE, 33,
                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(49, 49, 49)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(subtituloPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, 33,
                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(preciotxt, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                        javax.swing.GroupLayout.DEFAULT_SIZE,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(66, 66, 66)
                                .addComponent(botonGuardarDatosInsertar, javax.swing.GroupLayout.PREFERRED_SIZE, 33,
                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(38, 38, 38)));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE,
                                javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE));
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE,
                                javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE));
    }// </editor-fold>//GEN-END:initComponents

    private void nombretxtMousePressed(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_nombretxtMousePressed
        if (nombretxt.getText().equals("Ingrese el nombre del traje")) {
            nombretxt.setText("");
            nombretxt.setForeground(Color.white);
        }
    }// GEN-LAST:event_nombretxtMousePressed

    private void nombretxtActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_nombretxtActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_nombretxtActionPerformed

    private void paistxtActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_paistxtActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_paistxtActionPerformed

    private void paisesActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_paistxtActionPerformed

    }// GEN-LAST:event_paistxtActionPerformed

    private void materialtxtMousePressed(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_materialtxtMousePressed
        if (materialtxt.getText().equals("Ingrese el material del traje")) {
            materialtxt.setText("");
            materialtxt.setForeground(Color.white);
        }
    }// GEN-LAST:event_materialtxtMousePressed

    private void materialtxtActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_materialtxtActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_materialtxtActionPerformed

    private void preciotxtMousePressed(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_preciotxtMousePressed
        if (preciotxt.getText().equals("Ingrese el precio del traje")) {
            preciotxt.setText("");
            preciotxt.setForeground(Color.white);
        }
    }// GEN-LAST:event_preciotxtMousePressed

    private void preciotxtActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_preciotxtActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_preciotxtActionPerformed

    private void botonGuardarDatosInsertarActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_botonGuardarDatosInsertarActionPerformed
        if (nombretxt.getText().isEmpty() || materialtxt.getText().isEmpty() || preciotxt.getText().isEmpty()) {
            javax.swing.JOptionPane.showMessageDialog(this, "Todos los campos deben estar completos");
            return;
        }
        TrajeModel traje = new TrajeModel(nombretxt.getText(), PaisEnum.values()[paises.getSelectedIndex()],
                Double.parseDouble(preciotxt.getText()), materialtxt.getText());
        controller.actualizarTraje(index, traje);
        
        javax.swing.JOptionPane.showMessageDialog(this, "Actualzo el viaje");
        index = -1;
        botonGuardarDatosInsertar.setText("Buscar");
    }// GEN-LAST:event_botonGuardarDatosInsertarActionPerformed

    private void botonBuscarTrajeActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_botonBuscarTrajeActionPerformed

        String nombre = JOptionPane.showInputDialog(this, "Ingrese el nombre del traje");

        int index = controller.buscarTraje(nombre);
        if (index != -1) {
            traje = controller.getTienda().listarTrajes().get(index);
            nombretxt.setText(traje.getNombre());
            preciotxt.setText(traje.getPrecio() + "");
            materialtxt.setText(traje.getMaterial());
            for (int i = 0; i < PaisEnum.values().length; i++) {
                if (PaisEnum.values()[i].equals(traje.getPaisOrigen())) {
                    paises.setSelectedIndex(i);
                    break;
                }
            }
            this.index = index;
            botonGuardarDatosInsertar.setText("Acutualizar");
        } else {
            JOptionPane.showMessageDialog(this, "No se encontro el traje");

        }
    }// GEN-LAST:event_botonBuscarTrajeActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonGuardarDatosInsertar;
    private javax.swing.JButton buscar;
    private TrajeModel traje;
    private int index = -1;

    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JTextField materialtxt;
    private javax.swing.JTextField nombretxt;
    private javax.swing.JTextField paistxt;
    private javax.swing.JComboBox<PaisEnum> paises;

    private javax.swing.JTextField preciotxt;
    private javax.swing.JLabel subtituloMaterial;
    private javax.swing.JLabel subtituloNombre;
    private javax.swing.JLabel subtituloPais;
    private javax.swing.JLabel subtituloPrecio;
    private javax.swing.JLabel tituloinsertar;
    // End of variables declaration//GEN-END:variables
}
