/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.trajes;
import java.awt.Color;
/**
 *
 * @author DELL
 */
public class actualizar extends javax.swing.JPanel {

    /**
     * Creates new form actualizar2
     */
    public actualizar() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        tituloActualizar = new javax.swing.JLabel();
        subtituloModificar = new javax.swing.JLabel();
        nombretxt = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        subtituloPregunta = new javax.swing.JLabel();
        botonBuscarTraje = new javax.swing.JButton();
        botonModificar = new javax.swing.JButton();
        CBNombre = new javax.swing.JCheckBox();
        CBPais = new javax.swing.JCheckBox();
        CBMaterial = new javax.swing.JCheckBox();
        CBPrecio = new javax.swing.JCheckBox();
        nombretxt1 = new javax.swing.JTextField();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(102, 0, 0));

        tituloActualizar.setFont(new java.awt.Font("Mongolian Baiti", 1, 36)); // NOI18N
        tituloActualizar.setForeground(new java.awt.Color(255, 255, 255));
        tituloActualizar.setText("Actualizar trajes");

        subtituloModificar.setFont(new java.awt.Font("Mongolian Baiti", 1, 18)); // NOI18N
        subtituloModificar.setForeground(new java.awt.Color(255, 255, 255));
        subtituloModificar.setText("Modificar traje");

        nombretxt.setBackground(new java.awt.Color(51, 51, 51));
        nombretxt.setFont(new java.awt.Font("Lucida Sans Unicode", 0, 12)); // NOI18N
        nombretxt.setForeground(new java.awt.Color(255, 255, 255));
        nombretxt.setText("Ingrese el nombre del traje");
        nombretxt.setBorder(null);
        nombretxt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                nombretxtMousePressed(evt);
            }
        });
        nombretxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nombretxtActionPerformed(evt);
            }
        });

        jSeparator1.setForeground(new java.awt.Color(0, 0, 0));

        subtituloPregunta.setFont(new java.awt.Font("Mongolian Baiti", 1, 18)); // NOI18N
        subtituloPregunta.setForeground(new java.awt.Color(255, 255, 255));
        subtituloPregunta.setText("¿Que desea modificar?");

        botonBuscarTraje.setBackground(new java.awt.Color(204, 204, 204));
        botonBuscarTraje.setText("Buscar traje");
        botonBuscarTraje.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        botonBuscarTraje.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonBuscarTrajeActionPerformed(evt);
            }
        });

        botonModificar.setBackground(new java.awt.Color(204, 204, 204));
        botonModificar.setText("Modificar");
        botonModificar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        botonModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonModificarActionPerformed(evt);
            }
        });

        CBNombre.setForeground(new java.awt.Color(255, 255, 255));
        CBNombre.setText("Nombre");
        CBNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CBNombreActionPerformed(evt);
            }
        });

        CBPais.setForeground(new java.awt.Color(255, 255, 255));
        CBPais.setText("Pais");
        CBPais.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CBPaisActionPerformed(evt);
            }
        });

        CBMaterial.setForeground(new java.awt.Color(255, 255, 255));
        CBMaterial.setText("Material");
        CBMaterial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CBMaterialActionPerformed(evt);
            }
        });

        CBPrecio.setForeground(new java.awt.Color(255, 255, 255));
        CBPrecio.setText("Precio");
        CBPrecio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CBPrecioActionPerformed(evt);
            }
        });

        nombretxt1.setBackground(new java.awt.Color(51, 51, 51));
        nombretxt1.setFont(new java.awt.Font("Lucida Sans Unicode", 0, 12)); // NOI18N
        nombretxt1.setForeground(new java.awt.Color(255, 255, 255));
        nombretxt1.setText("Ingrese el nuevo dato");
        nombretxt1.setBorder(null);
        nombretxt1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                nombretxt1MousePressed(evt);
            }
        });
        nombretxt1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nombretxt1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(subtituloPregunta))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(209, 209, 209)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(CBMaterial)
                            .addComponent(CBPais)
                            .addComponent(CBPrecio))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(botonModificar, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addGap(135, 135, 135)
                        .addComponent(tituloActualizar)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(subtituloModificar)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(21, 21, 21)
                                .addComponent(nombretxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 62, Short.MAX_VALUE)
                                .addComponent(botonBuscarTraje, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(23, 23, 23))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(211, 211, 211)
                    .addComponent(CBNombre)
                    .addContainerGap(222, Short.MAX_VALUE)))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(170, 170, 170)
                    .addComponent(nombretxt1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(205, Short.MAX_VALUE)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tituloActualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(13, 13, 13)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(botonBuscarTraje, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(subtituloModificar, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(nombretxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(32, 32, 32)
                .addComponent(subtituloPregunta, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(2, 2, 2)
                .addComponent(CBPais)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(CBMaterial)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(CBPrecio)
                .addGap(38, 38, 38)
                .addComponent(botonModificar, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(199, 199, 199))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(139, 139, 139)
                    .addComponent(CBNombre)
                    .addContainerGap(344, Short.MAX_VALUE)))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(241, 241, 241)
                    .addComponent(nombretxt1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(242, Short.MAX_VALUE)))
        );

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void nombretxtMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nombretxtMousePressed
        if (nombretxt.getText().equals("Ingrese el nombre del traje")){
            nombretxt.setText("");
            nombretxt.setForeground(Color.white);
        }
    }//GEN-LAST:event_nombretxtMousePressed

    private void nombretxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nombretxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nombretxtActionPerformed

    private void botonBuscarTrajeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonBuscarTrajeActionPerformed
                                    
        if (nombretxt.getText().equals("Ingrese el nombre del traje") || nombretxt.getText().isEmpty()){
            //JOptionPane.showMessageDialog(this,"Ingresa el nombre a buscar");
            return;
        }
        /*
        dulceResultado = controller.buscarPorNombre(nombretxt.getText());
        if(dulceResultado != null){
            JOptionPane.showMessageDialog(this,"Dulce encontrado");
            return;
        }else{
            JOptionPane.showMessageDialog(this,"No se encontro el dulce: "+nombretxt.getText());
            return;
        }
        */
    }//GEN-LAST:event_botonBuscarTrajeActionPerformed

    private void botonModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonModificarActionPerformed
        /*
        if(CBNombre.isSelected() != false){
            dulceResultado.setNombre(change.getText());
        }
        if(CBPrecio.isSelected() != false){
            dulceResultado.setPrecio(Integer.parseInt(change.getText()));
        }
        if(CBMaterial.isSelected() != false){
            dulceResultado.setDescripcion(change.getText());
        }
        
        
        JOptionPane.showMessageDialog(this,"Dulce modificado");
        nombretxt.setText("");
        change.setText("");
        CBNombre.setSelected(false);
        CBPrecio.setSelected(false);
        CBMaterial.setSelected(false);
        CBPais.setSelected(false);  
        */
    
    }//GEN-LAST:event_botonModificarActionPerformed

    private void CBNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CBNombreActionPerformed
        CBPais.setSelected(false);
        CBNombre.setSelected(true);
        CBPrecio.setSelected(false);
        CBMaterial.setSelected(false); 
    }//GEN-LAST:event_CBNombreActionPerformed

    private void CBPaisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CBPaisActionPerformed
        CBPais.setSelected(true);
        CBNombre.setSelected(false);
        CBPrecio.setSelected(false);
        CBMaterial.setSelected(false); 
    }//GEN-LAST:event_CBPaisActionPerformed

    private void CBMaterialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CBMaterialActionPerformed
        CBPais.setSelected(false);
        CBNombre.setSelected(false);
        CBPrecio.setSelected(false);
        CBMaterial.setSelected(true);
    }//GEN-LAST:event_CBMaterialActionPerformed

    private void CBPrecioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CBPrecioActionPerformed
        CBPais.setSelected(false);
        CBNombre.setSelected(false);
        CBPrecio.setSelected(true);
        CBMaterial.setSelected(false); 
    }//GEN-LAST:event_CBPrecioActionPerformed

    private void nombretxt1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nombretxt1MousePressed
        if (nombretxt1.getText().equals("Ingrese el nuevo dato")){
            nombretxt1.setText("");
            nombretxt1.setForeground(Color.white);
        }
    }//GEN-LAST:event_nombretxt1MousePressed

    private void nombretxt1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nombretxt1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nombretxt1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox CBMaterial;
    private javax.swing.JCheckBox CBNombre;
    private javax.swing.JCheckBox CBPais;
    private javax.swing.JCheckBox CBPrecio;
    private javax.swing.JButton botonBuscarTraje;
    private javax.swing.JButton botonModificar;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField nombretxt;
    private javax.swing.JTextField nombretxt1;
    private javax.swing.JLabel subtituloModificar;
    private javax.swing.JLabel subtituloPregunta;
    private javax.swing.JLabel tituloActualizar;
    // End of variables declaration//GEN-END:variables
}
