/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package views.trajes;
import java.util.ArrayList;

import models.TrajeModel;
/**
 *
 * @author DELL
 */
public class Listado extends javax.swing.JPanel {
    private String lista = "";
    /**
     * Creates new form actualizar2
     */
    public Listado(ArrayList<TrajeModel> trajes) {
        
         for(TrajeModel traje : trajes){
            lista += traje.toString()+"\n";
        }
        initComponents();
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        textArea = new javax.swing.JTextArea();
        textArea.setFont(new java.awt.Font("Mongolian Baiti", 1, 24)); // NOI18N
        textArea.setText(lista);
        textArea.setColumns(25);        
        textArea.setRows(15);
        textArea.setEnabled(false);

        scroll = new javax.swing.JScrollPane(textArea);
        
        add(scroll, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 500, 500));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JScrollPane scroll;
    private javax.swing.JTextArea textArea;
    // End of variables declaration//GEN-END:variables
}
